config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
  devise_for :admins, controllers: {
  	sessions: 'devise/admin/sessions',
  	passwords: 'devise/admin/passwords',
  	registrations: 'devise/admin/registrations'
  }
  devise_for :customers, controllers: {
  	sessions: 'devise/customers/sessions',
  	passwords: 'devise/customers/passwords',
  	registrations: 'devise/customers/registrations'
  }
  resource :customer, only: [:show, :edit, :update, :destroy]
  resources :shippings, except: [:show]
  resources :items, only: [:index, :show]
  resources :cart_items, only: [:index, :create, :update, :destroy]

  namespace :admin do
    resources :items
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :customer
	belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shippings
  has_many :cart_items
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
	attachment :image
	belongs_to :genre
	has_many :cart_items
end

app/models/shipping.rb
class Shipping < ApplicationRecord
	belongs_to :customer
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

	def index
		@genres = Genre.all
		@genre = Genre.new
	end
	def create
		@genre = Genre.new(genre_params)
		if @genre.save
			redirect_to admin_genres_path
			flash[:notice_genre] = 'ジャンルを追加しました！'
		else
			@genres = Genre.all
			render 'index'
		end
	end
	def edit
		@genre = Genre.find(params[:id])
	end
	def update
		@genre = Genre.find(params[:id])
		if @genre.update(genre_params)
			redirect_to admin_genres_path
			flash[:notice_update] = 'ジャンルを更新しました！'
		else
			reder 'edit'
		end
	end
	private
	def genre_params
		params.require(:genre).permit(:name,:is_active)
	end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

	def new
		@item = Item.new
		@genres = Genre.all
	end
	def create
		@item = Item.new(item_params)
		@genres = Genre.all
		if @item.save
			redirect_to admin_items_path
      		flash[:notice_new] = "商品が登録されました!"
    	else
      		render :new
    	end
	end
	def index
		@items = Item.all
	end
	def show
		@item = Item.find(params[:id])
	end
	def edit
		@item = Item.find(params[:id])
		@genres = Genre.all
	end
	def update
		@item = Item.find(params[:id])
		@genres = Genre.all
		if @item.update(item_params)
			redirect_to admin_item_path(@item)
			flash[:notice_update] = "商品が更新されました！"
		else
			render :edit
		end
	end

	private
    def item_params
      params.require(:item).permit(:genre_id, :name, :introduction, :image, :price, :is_sold, :created_at, :updated_at)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
		case resource
			when Admin
			admin_root_path
			when Customer
			customer_path(current_customer)
		end
	end
	protected
		def configure_permitted_parameters
			devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :is_deleted])
		end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

	def create
		@cart_item = CartItem.new(cart_item_params)
		@cart_item.customer_id = current_customer.id
		if @cart_item.save
			redirect_to cart_items_path
		else
		end

	end
	
	def index
    	@cart_items = CartItem.where(customer_id: current_customer.id)
    	@subtotal = 0
    	@cart_items.each do |cart_item|
      		@subtotal += BigDecimal(cart_item.item.price) * cart_item.quantity * BigDecimal("1.08")
    	end

  	end

	private
    def cart_item_params
      params.require(:cart_item).permit(:item_id, :quantity)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	def show
		@customer = current_customer
	end
	def edit
		@customer = current_customer
	end
	def update
		@customer = current_customer
		if @customer.update(customer_params)
			redirect_to customer_path
			flash[:notice_update] = "会員情報が更新されました！"
		else
			render 'edit'
		end
	end
	private
	def customer_params
		params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postcode,:address,:phone_number,:email)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def top
		@items = Item.all
		@genres = Genre.all
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@items = Item.all
	end
	def show
		@item = Item.find(params[:id])
		@cart_item = CartItem.new
	end

end

app/controllers/shippings_controller.rb
class ShippingsController < ApplicationController

	def index
		@shippings = current_customer.shippings.all
		@shipping = Shipping.new
	end
	def create
		@shipping = Shipping.new(shipping_params)
		@shipping.customer_id = current_customer.id
		if @shipping.save
			flash[:notice_create] = "新規配送先を登録しました！"
			redirect_to shippings_path
		else
			@shippings = current_customer.shippings.all
			render :index
		end
	end
	def edit
		@shipping = Shipping.find(params[:id])
	end
	def update
		@shipping = Shipping.find(params[:id])
		if @shipping.update(shipping_params)
			flash[:notice_fix] = "配送先情報を修正しました！"
			redirect_to shippings_path
		else
			render :edit
		end
	end
	def destroy
		@shipping = Shipping.find(params[:id])
		if @shipping.destroy
			flash[:notice_destroy] = "配送先を削除しました！"
			redirect_to shippings_path
		end
	end


	private
	def shipping_params
    	params.require(:shipping).permit(:postcode, :address, :address_name)
	end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/views/admin/genres/edit.html.erb
<div class="container mx-auto" style="width: 700px;">
	<%= form_for(@genre, url: {controller:"genres", action:"update"}) do |f| %>
	<h3 class="text-center">ジャンル編集</h3>
	<br>
	<div class="row admin-genre-edit">
		<%= f.text_field :name, class:"form-control" %><br>
		<%= f.radio_button :is_active, :true %>有効
		<%= f.radio_button :is_active, :false %>無効<br>
		<%= f.submit "変更を保存する", class:"btn btn-outline-primary" %>
	</div>
	<% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
	<%= form_for(@genre, url: {controller: "genres", action: "create"}) do |f| %>
	<h3 class="text-center">新規ジャンル追加</h3>
	<%= flash[:notice_genre] %>
	<div class="row errors mx-auto">
		<% if @genre.errors.any? %>
		    <h5><%= @genre.errors.count %>件のエラーがあります</h5>
		    <ul>
		        <% @genre.errors.full_messages.each do |message| %>
		            <li><%= message %></li>
		        <% end %>
		    </ul>
		<% end %>
	</div>
	<div class="row admin-genre-create mx-auto" style="width: 500px;">
		<%= f.text_field :name, class:"form-control mb-2" %>
		<%= f.radio_button :is_active, :true %>有効
		<%= f.radio_button :is_active, :false %>無効
		<%= f.submit "追加", class:"btn btn-outline-primary" %>
	</div>
	<% end %>
	<br>
	<br>
	<div class="row admin-genre-index mx-auto text-center" style="width: 700px;">
		<table class="table">
			<thead>
				<th>ジャンル</th>
				<th>状態</th>
				<th></th>
			</thead>
			<tbody>
				<% @genres.each do |genre| %>
				<tr>
					<td><%= genre.name %></td>
					<td>
						<% if genre.is_active? %>
							<p>有効</p>
						<% else %>
							<p>無効</p>
						<% end %>
					</td>
					<td>
						<%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-outline-primary" %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/admin/items/edit.html.erb
<div class="container mx-auto admin-items-new">
	<h2 class="text-center">商品編集</h2>
	<br>
	<div class="row errors">
	<% if @item.errors.any? %>
         <h2><%= @item.errors.count %>件のエラーがあります</h2>
            <ul>
               <% @item.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
            </ul>
    <% end %>
	</div>
	<%= form_for(@item, url: {controller: "items", action: "update"}) do |f| %>
	<div class="row">
		<div class="col-6">
			<%= f.attachment_field :image %>
		</div>
		<div class="col-6">
			<tr>
				<th><%= f.label :"商品名" %></th>
				<td><%= f.text_field :name, class:"form-control" %></td>
			</tr>
			<br>
			<tr>
				<th><%= f.label :"商品説明" %></th>
				<td><%= f.text_field :introduction, class:"form-control" %></td>
			</tr>
			<br>
			<tr>
				<th><%= f.label :"ジャンル" %></th>
				<td><%= f.collection_select(:genre_id, @genres, :id, :name) %></td>
			</tr>
			<br>
			<tr>
				<th><%= f.label :"税抜き価格" %></th>
				<td><%= f.number_field :price, class:"form-control" %></td>
			</tr>
			<br>
			<tr>
				<th><%= f.label :"販売ステータス" %></th>
				<td><%= f.select :is_sold, [["販売中","false"],["売り切れ","true"]], class:"form-control" %></td>
			</tr>
			<br>
			<br>
			<%= f.submit "変更を保存", class:"btn btn-outline-primary"%>
		</div>
	</div>
	<% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container mx-auto" style="width: 600px;">
	<h3 class="text-center">商品一覧</h3><br>
	<font color="red">
	<%= flash[:notice_new] %>
	</font>
	<div class="row admin-item-index text-center">
		<table class="table">
			<thead>
				<tr>
					<th>商品ID</th>
					<th>商品名</th>
					<th>税抜価格</th>
					<th>ジャンル</th>
					<th>ステータス</th>
				</tr>
			</thead>
			<tbody>
				<% @items.each do |item| %>
				<tr>
					<td><%= item.id %></td>
					<td><%= item.name %></td>
					<td><%= item.price %></td>
					<td><%= item.genre.name %></td>
					<td>
						<% if item.is_sold? %>
							<p>売り切れ</p>
						<% else %>
							<p>販売中</p>
						<% end %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/admin/items/new.html.erb
<div class="container mx-auto admin-items-new">
	<h2 class="text-center">商品新規登録</h2>
	<br>
	<div class="row errors">
	<% if @item.errors.any? %>
        <div id="error_explanation">
         <h2><%= pluralize(@item.errors.count, "error") %> prohibited this user from being saved:</h2>
          	<ul>
          		<% @item.errors.full_messages.each do |msg| %>
            		<li><%= msg %></li>
          		<% end %>
          	</ul>
        </div>
    <% end %>
	</div>
	<%= form_for(@item, url: {controller: "items", action: "create"}) do |f| %>
	<div class="row">
		<div class="col-6">
			<%= f.attachment_field :image %>
		</div>
		<div class="col-6">
			<tr>
				<th><%= f.label :"商品名" %></th>
				<td><%= f.text_field :name, class:"form-control" %></td>
			</tr>
			<br>
			<tr>
				<th><%= f.label :"商品説明" %></th>
				<td><%= f.text_field :introduction, class:"form-control" %></td>
			</tr>
			<br>
			<tr>
				<th><%= f.label :"ジャンル" %></th>
				<td><%= f.collection_select(:genre_id, @genres, :id, :name) %></td>
			</tr>
			<br>
			<tr>
				<th><%= f.label :"税抜き価格" %></th>
				<td><%= f.number_field :price, class:"form-control" %></td>
			</tr>
			<br>
			<tr>
				<th><%= f.label :"販売ステータス" %></th>
				<td><%= f.select :is_sold, [["販売中","false"],["売り切れ","true"]], class:"form-control" %></td>
			</tr>
			<br>
			<br>
			<%= f.submit "新規登録", class:"btn btn-outline-primary"%>
		</div>
	</div>
	<% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container mx-auto admin-items-show">
	<h2 class="text-center">商品詳細</h2>
	<%= flash[:notice_update] %>
	<br>
	<div class="row">
		<div class="col-6">
			<%= attachment_image_tag @item, :image, :fill, 300, 250 %>
		</div>
		<div class="col-6">
			<div class="field">
				<p>【商品名】</p>
				<p>　<%= @item.name %></p>
			</div>
			<br>
			<div class="field">
				<p>【商品紹介】</p>
				<p>　<%= @item.introduction %></p>
			</div>
			<br>
			<div class="field">
				<p>【ジャンル】</p>
				<p>　<%= @item.genre.name %></p>
			</div>
			<br>
			<div class="field">
				<p>【税抜価格(税込価格)】</p>
				<p>　<%= @item.price %>(<%= @item.price * 1.08 %>)円</p>
			</div>
			<br>
			<div class="field">
				<p>【販売ステータス】</p>
				<p>　
					<% if @item.is_sold? %>
						売り切れ
					<% else %>
						販売中
					<% end %>
				</p>
			</div>
			<div class="submit">
				<%= link_to '編集する', edit_admin_item_path(@item), class:"btn btn-outline-primary" %>
			</div>
		</div>
	</div>
</div>

app/views/cart_items/index.html.erb
<div class="container">
	<h1 class="text-center">Shopping Cart</h1>

	<div class="row">
  		<table class="table table-bordered mx-auto">
    		<thead class="thead-light">
      			<tr>
        			<th scope="col">商品名</th>
        			<th scope="col">単価</th>
        			<th scope="col">数量</th>
        			<th scope="col">小計</th>
        			<th scope="col"></th>
      			</tr>
    		</thead>
    		<% @cart_items.each do |cart_item| %>
      		<tbody>
        		<tr>
          			<td scope="row">
          				<%= attachment_image_tag cart_item.item, :image,:fill, 90, 60 %>
          				<%= cart_item.item.name %>
          			</td>
          			<td scope="row"><%= number_to_currency((BigDecimal(cart_item.item.price) * BigDecimal("1.08")).ceil) %></td>
          			<td scope="row">
            			<%= form_for cart_item, url: cart_item_path(cart_item), method: :patch  do |f|%>
              				<%= f.number_field :quantity %>
              				<%= f.submit'変更',  class: 'btn btn-primary' %>
             			<% end %>
          			</td>
          			<td scope="row"><%= number_to_currency((BigDecimal(cart_item.item.price) * BigDecimal("1.08") * cart_item.quantity).ceil) %></td>
          			<td scope="row"><%= link_to '削除する', cart_item_path(cart_item), method: :delete, class: 'btn btn-danger'%></td>
        		</tr>
      		</tbody>
    		<% end %>
  		</table>
	</div>
</div>

app/views/customers/edit.html.erb
<%= form_for(@customer) do |f| %>
<div class="container mx-auto" style="width: 600px;">
	<div class="row text-center">
		<h2>登録情報編集</h2>
		<p>退会する</p>
	</div>
	<div class="edit-group row">
		<table class="table">
			<tr>
				<th>氏名</th>
				<td><%=f.text_field :last_name,class:"form-control" %></td><td><%=f.text_field :first_name,class:"form-control" %></td>
			</tr>
			<tr>
				<th>フリガナ</th>
				<td><%= f.text_field :last_name_kana,class:"form-control" %></td><td><%= f.text_field :first_name_kana,class:"form-control" %></td>
			</tr>
			<tr>
				<th>郵便番号</th>
				<td><%= f.text_field :postcode,class:"form-control" %></td>
			</tr>
			<tr>
				<th>住所</th>
				<td><%= f.text_field :address,class:"form-control" %></td>
			</tr>
			<tr>
				<th>電話番号</th>
				<td><%= f.text_field :phone_number,class:"form-control" %></td>
			</tr>
			<tr>
				<th>メールアドレス</th>
				<td><%= f.text_field :email,class:"form-control" %></td>
			</tr>
		</table>
	</div>
	<br>
	<%= f.submit "保存する", class:"btn btn-outline-primary mb-4" %>
</div>
<% end %>

app/views/customers/show.html.erb
<div class="container mx-auto" style="width: 600px;">
	<h2 class="text-center">マイページ</h2>
	<br>
	<div class="row">
		<%= flash[:notice_update] %>
	</div>
	<div class="row">
		<div class="col-3">
			<h4>登録情報</h4>
		</div>
		<div class="col-3">
			<%= link_to "編集する", edit_customer_path, class:"btn btn-outline-primary mb-2" %>
		</div>
		<div class="col-5">
			<%= link_to "パスワードを変更する", edit_customer_registration_path, class:"btn btn-outline-primary mb-2" %>
		</div>
	</div>
	<br>
	<div class="row">
		<table class="table">
			<tr>
				<th>氏名</th>
				<td><%= @customer.last_name %><%= @customer.first_name %></td>
			</tr>
			<tr>
				<th>フリガナ</th>
				<td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
			</tr>
			<tr>
				<th>郵便番号</th>
				<td><%= @customer.postcode %></td>
			</tr>
			<tr>
				<th>住所</th>
				<td><%= @customer.address %></td>
			</tr>
			<tr>
				<th>電話番号</th>
				<td><%= @customer.phone_number %></td>
			</tr>
			<tr>
				<th>メールアドレス</th>
				<td><%= @customer.email %></td>
			</tr>
		</table>
	</div>
	<br>
	<div class="row">
		<div class="col-lg-6 text-center">
			<h3>配送先</h3>
			<%= link_to "一覧を見る", shippings_path, class:"btn btn-outline-primary mb-2" %>
		</div>
		<div class="col-lg-6 text-center">
			<h3>注文履歴</h3>
			<h5>一覧を見る</h5>
		</div>
	</div>
</div>

app/views/items/index.html.erb
保留
<!-- <div class="container">
	<div class="row item-index mx-auto">
		<h3 class="text-center">LINE UP</h3>
	<div class="col-3">
		<h5>ジャンル</h5>
		<table class="table">
		</table>
	</div>
	</div>
</div> -->

app/views/items/show.html.erb
<div class="container mx-auto item-show">
	<h2 class="text-center">商品詳細</h2>
	<br>
	<div class="row">
		<div class="col-6">
			<%= attachment_image_tag @item, :image, :fill, 300, 250 %>
		</div>
		<div class="col-6">
			<div class="item-info">
				<div class="field">
					<p>　<%= @item.name %></p>
				</div>
				<div class="field">
					<p>　<%= @item.introduction %></p>
				</div>
				<div class="field">
					<p>　<%= @item.price * 1.08 %>円(税込)</p>
				</div>
			</div>
			<br>
			<%= form_for @cart_item do |f| %>
				<%= f.hidden_field :item_id, value: @item.id %>
			<div class="item-select">
				<div class="select-q">
					<%= f.select :quantity, options_for_select((1...6).to_a), include_blank: "個数選択" %>
				</div>
				<br>
				<div class="cart_in">
					<%= f.submit "カートに入れる", class:"btn btn-outline-success btn-sm" %>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/shippings/edit.html.erb
<div class="container mx-auto" style="width: 400px;">
<%= form_for (@shipping) do |f| %>
	<h3 class="text-center">配送先編集</h3>
	<br>
	<div class="shipping-edit">
		<tr>
			<th>郵便番号</th>
			<td><%= f.text_field :postcode, class:"form-control" %></td>
		</tr>
		<br>
		<tr>
			<th>住所</th>
			<td><%= f.text_field :address, class:"form-control" %></td>
		</tr>
		<br>
		<tr>
			<th>宛名</th>
			<td><%= f.text_field :address_name, class:"form-control" %></td>
		</tr>
		<br>
		<%= f.submit "編集する",class:"btn btn-outline-primary" %>
	</div>
<% end %>
</div>

app/views/shippings/index.html.erb
<div class="container">
<div class="shipping-new mx-auto" style="width: 400px;">
<%= form_for @shipping do |f| %>
	<h3 class="text-center">新規配送先登録</h3>
	<br>
	<%= flash[:notice_create] %>
 	<div class="shipping-create">
 		<tr>
 			<th>郵便番号</th>
 			<td><%= f.text_field :postcode, class:"form-control mb-2" %></td>
 		</tr>
 		<tr>
 			<th>住所</th>
 			<td><%= f.text_field :address, class:"form-control mb-2" %></td>
 		</tr>
 		<tr>
 			<th>宛名</th>
 			<td><%= f.text_field :address_name, class:"form-control mb-2" %></td>
 		</tr>
 		<%= f.submit "登録する", class:"btn btn-outline-primary mb-4" %>
 	</div>
<% end %>
</div>
<div class="shipping-index mx-auto" style="width: 800px;">
	<h3 class="text-center">配送先一覧</h3>
	<br>
	<%= flash[:notice_fix] %>
	<%= flash[:notice_destroy] %>
	<table class="table">
		<tr>
			<th>郵便番号</th>
			<th>住所</th>
			<th>宛名</th>
			<th></th>
			<th></th>
		</tr>
		<% @shippings.each do |shipping| %>
		<tr>
			<td><%= shipping.postcode %></td>
			<td><%= shipping.address %></td>
			<td><%= shipping.address_name %></td>
			<td><%= link_to "編集する", edit_shipping_path(shipping.id), class:"btn btn-outline-primary mb-2" %></td>
			<td><%= link_to "削除する", shipping_path(shipping.id), method: :delete, class:"btn btn-outline-danger mb-2" %></td>
		</tr>
		<% end %>
	</table>
	<%= link_to "<マイページに戻る", customer_path %>
</div>
</div>